Algoritmo "Idade verdadeiro ou não "

Var
   ano, nasceu, idade: inteiro

Inicio
      escreva("em que ano estamos? ")
      leia(ano)
      escreva("em que ano voce nasceu? ")
      leia(nasceu)
      idade <- ano-nasceu
      escreva("em", ano, " sua idade será", idade, " anos")
      se (idade >= 21) então
         escreval(", parabens voce atigiu a maior idade!")
      fimse


Fimalgoritmo